### ISSUE TITLE
windows OS train faster-RCNN error!

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#309]
When I train faster-RCNN on windows, It will download caffe VGG16 model and convert into .npz
 file. But then it will report error:   ( I haven't train faster-RCNN on Linux yet, Maybe it will report same error, I will test it on linux soon)
```
Traceback (most recent call last):
  File "examples/faster_rcnn/train.py", line 128, in <module>
    main()
  File "examples/faster_rcnn/train.py", line 124, in main
    trainer.run()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\training\trainer.py", line 296, in run
    update()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\training\updater.py", line 177, in update
    self.update_core()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\training\updater.py", line 181, in update_core
    batch = self._iterators['main'].next()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\iterators\multiprocess_iterator.py", line 73, in __next__
    self._init()  # start workers
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\iterators\multiprocess_iterator.py", line 142, in _init
    self._init_process()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\chainer-2.0.0-py3.5.egg\chainer\iterators\multiprocess_iterator.py", line 168, in _init_process
    worker.start()
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.transform'

```

**Comment by yuyu2172** [comment]
Thanks for reporting.
We fixed that issue. #309
