### ISSUE TITLE
SSD: Forwarding fails with cuDNN Error on TK1

### ISSUE THREAD

**Issue by furushchev** [chainer/chainercv#344]
We use Jetson TK1 for deep learning, and I installed chainer and chainercv.
However predicting dies on forwarding network.

```bash
~/chainercv/examples/ssd$ python demo.py --gpu 0 --model ssd300  ../../../000401.jpg
Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    main()
  File "demo.py", line 36, in main
    bboxes, labels, scores = model.predict([img])
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 259, in predict
    loc, conf = self(x)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 140, in __call__
    return self.multibox(self.extractor(x))
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/multibox.py", line 79, in __call__
    loc = self.loc[i](x)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/convolution_2d.py", line 109, in __call__
    deterministic=self.deterministic)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 417, in convolution_2d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 310, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 144, in forward_gpu
    y_desc.value, y.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 692, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:7108)
  File "cupy/cuda/cudnn.pyx", line 705, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:6920)
  File "cupy/cuda/cudnn.pyx", line 417, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:2048)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM: CUDNN_STATUS_BAD_PARAM
```

My environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

```
$ uname -a
Linux 3.10.40-gdacac96 #1 SMP PREEMPT Thu Jun 25 15:25:11 PDT 2015 armv7l armv7l armv7l GNU/Linux
```

```
pip freeze | grep -e chainer -e numpy -e matplotib -e scipy
chainer==1.24.0
chainercv==0.4.11
numpy==1.13.1
scipy==0.19.1
```

Any idea for debugging this issue?

**Comment by furushchev** [comment]
Related? https://github.com/chainer/chainer/issues/787

**Comment by furushchev** [comment]
Appended "print" before conv

```diff
diff --git a/chainercv/links/model/ssd/multibox.py b/chainercv/links/model/ssd/multibox.py
index 634aff0..e011cb3 100644
--- a/chainercv/links/model/ssd/multibox.py
+++ b/chainercv/links/model/ssd/multibox.py
@@ -76,6 +76,7 @@ class Multibox(chainer.Chain):
         locs = list()
         confs = list()
         for i, x in enumerate(xs):
+            print i, x.shape, x.dtype
             loc = self.loc[i](x)
             loc = F.transpose(loc, (0, 2, 3, 1))
             loc = F.reshape(loc, (loc.shape[0], -1, 4))
```

output:

```bash
$ python ./ssd/demo.py --model ssd300 --gpu 0 left0000.jpg
0 (1, 512, 38, 38) float32
1 (1, 1024, 19, 19) float32
2 (1, 512, 10, 10) float32
3 (1, 256, 5, 5) float32
4 (1, 256, 3, 3) float32
5 (1, 256, 1, 1) float32
Traceback (most recent call last):
  File "./ssd/demo.py", line 45, in <module>
    main()
  File "./ssd/demo.py", line 36, in main
    bboxes, labels, scores = model.predict([img])
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 259, in predict
    loc, conf = self(x)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 140, in __call__
    return self.multibox(self.extractor(x))
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/multibox.py", line 80, in __call__
    loc = self.loc[i](x)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/convolution_2d.py", line 109, in __call__
    deterministic=self.deterministic)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 417, in convolution_2
d
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 310, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/convolution_2d.py", line 144, in forward_gpu
    y_desc.value, y.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 692, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:7108)
  File "cupy/cuda/cudnn.pyx", line 705, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:6920)
  File "cupy/cuda/cudnn.pyx", line 417, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:2048)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM: CUDNN_STATUS_BAD_PARAM
```

**Comment by Hakuyume** [comment]
I have never seen that error. Does it work without cudnn?

**Comment by furushchev** [comment]
@Hakuyume Thank you for response! Without cuDNN, I met another error on `F.concat` part.

```diff
diff --git a/chainercv/links/model/ssd/multibox.py b/chainercv/links/model/ssd/multibox.py
index 634aff0..d080fea 100644
--- a/chainercv/links/model/ssd/multibox.py
+++ b/chainercv/links/model/ssd/multibox.py
@@ -46,8 +46,11 @@ class Multibox(chainer.Chain):
             initial_bias = initializers.Zero()
         init = {'initialW': initialW, 'initial_bias': initial_bias}
 
-        for ar in aspect_ratios:
+        for i, ar in enumerate(aspect_ratios):
             n = (len(ar) + 1) * 2
+            if i == len(aspect_ratios) - 1:
+                # disable cudnn only on the last conv2d
+                init.update({"use_cudnn": False})
             self.loc.add_link(L.Convolution2D(None, n * 4, 3, pad=1, **init))
             self.conf.add_link(L.Convolution2D(
                 None, n * self.n_class, 3, pad=1, **init))
```

Output:

```
python examples/ssd/demo.py --model ssd300 --gpu 0 examples/left0000.jpg 
Traceback (most recent call last):
  File "examples/ssd/demo.py", line 45, in <module>
    main()
  File "examples/ssd/demo.py", line 36, in main
    bboxes, labels, scores = model.predict([img])
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 259, in predict
    loc, conf = self(x)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd.py", line 140, in __call__
    return self.multibox(self.extractor(x))
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/multibox.py", line 93, in __call__
    loc = F.concat(locs, axis=1)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/array/concat.py", line 87, in concat
    return Concat(axis=axis)(*xs)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/array/concat.py", line 43, in forward
    return xp.concatenate(xs, axis=self.axis),
  File "/usr/local/lib/python2.7/dist-packages/cupy/manipulation/join.py", line 49, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/core.pyx", line 2072, in cupy.core.core.concatenate_method (cupy/core/core.cpp:63848)
  File "cupy/core/core.pyx", line 2115, in cupy.core.core.concatenate_method (cupy/core/core.cpp:63748)
  File "cupy/core/core.pyx", line 2139, in cupy.core.core.concatenate (cupy/core/core.cpp:64178)
ValueError: Buffer dtype mismatch, expected 'Py_ssize_t' but got 'long long'
```

**Comment by Hakuyume** [comment]
`use_cudnn` option in `Convolution2D.__init__` was removed in Chainer v2. https://docs.chainer.org/en/stable/upgrade.html#configurations-are-added-and-replace-some-of-existing-global-flags

**Comment by furushchev** [comment]
@Hakuyume Yes. But I use TK1 and AFAIK, chainer v2 does not support TK1, so we must use chainer v1 on TK1.

FYI: Please see my python environment attached above.

**Comment by Hakuyume** [comment]
@furushchev Sorry. I missed your environment. For v1, it is OK.

**Comment by yuyu2172** [comment]
Maybe, the spatial size of the input needs to be equal or bigger than the size of a kernel in older cuDNN.

**Comment by yuyu2172** [comment]
I have written a dirty fix to make the kernel size to 1x1.
Can you add the following method to `Multibox`?

```python
class Multibox(chainer.Chain):

...
    def convert_last_link_to_1x1(self):
        out_c, in_c, kh, kw = self.loc[-1].W.shape
        l = L.Convolution2D(in_c, out_c, 1, pad=0)
        l.W.data[:, :, 0, 0] = self.loc[-1].W.data[:, :, 1, 1]
        l.b.data = self.loc[-1].b.data
        self.loc._children.remove(self.loc[-1])
        self.loc.append(l)

        out_c, in_c, kh, kw = self.conf[-1].W.shape
        l = L.Convolution2D(in_c, out_c, 1, pad=0)
        l.W.data[:, :, 0, 0] = self.conf[-1].W.data[:, :, 1, 1]
        l.b.data = self.conf[-1].b.data
        self.conf._children.remove(self.conf[-1])
        self.conf.append(l)

```

and call the following command in a demo?

```
    ... (After initializing with pretrained weight)
    model.multibox.convert_last_link_to_1x1()
```

The `demo.py` produced the same output with this change.

**Comment by furushchev** [comment]
@yuyu2172 Thx for advice! I'll try it..

**Comment by yuyu2172** [comment]
Let's close it.
32-bit is currently out of scope.

**Comment by furushchev** [comment]
@yuyu2172 @Hakuyume Thanks anyway!
