### ISSUE TITLE
`download_model()` fails if directory is not present

### ISSUE THREAD

**Issue by tgpfeiffer** [chainer/chainercv#356]
If the directory `$CHAINER_DATASET_ROOT/pfnet/chainercv/models/` is not present, then calls of `download_model()` fail with an error as the following:

```
Downloading ...
From: https://github.com/yuyu2172/share-weights/releases/download/0.0.3/ssd_vgg16_imagenet_2017_06_09.npz
To: /home/user/.chainer/dataset/_dl_cache/286b14d9978d61e62eece136d00359e5
  %   Total    Recv       Speed  Time left
Traceback (most recent call last):
  File "chainercv/examples/ssd/train.py", line 196, in <module>
    main()
  File "chainercv/examples/ssd/train.py", line 132, in main
    pretrained_model='imagenet')
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd_vgg16.py", line 305, in __init__
    n_fg_class, pretrained_model, self._models)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/ssd/ssd_vgg16.py", line 238, in _check_pretrained_model
    path = download_model(model['url'])
  File "/usr/local/lib/python2.7/dist-packages/chainercv/utils/download.py", line 115, in download_model
    os.rename(cache_path, path)
OSError: [Errno 2] No such file or directory
```

If I `mkdir -p` the directory beforehand, download succeeds.

This is for version 0.6.0.

**Comment by Hakuyume** [comment]
@tgpfeiffer Thank you for reporting. I tried to reproduce the error but I couldn't.
Could you tell me the steps to reproduce?

```
$ cd chainercv/examples/ssd/
$ rm -r ~/.chainer/dataset/
$ ls ~/.chainer/dataset/
ls: cannot access '***/.chainer/dataset/': No such file or directory
$ python demo.py ~/some_image.jpg
Downloading ...
From: https://github.com/yuyu2172/share-weights/releases/download/0.0.3/ssd300_voc0712_2017_06_06.npz
To: ***/.chainer/dataset/_dl_cache/39be0d7ab69efbab2387ccbf556b7e8d
  %   Total    Recv       Speed  Time left
100   93MiB   93MiB   2007KiB/s    0:00:00
(It shows the result of detection)
```

**Comment by tgpfeiffer** [comment]
I was able to track this issue down. My `/home/user/.chainer/dataset/pfnet` directory was not writable for the user and because Chainer does not report failure in creating dataset directories (https://github.com/chainer/chainer/issues/3057) the `os.rename()` call failed. This is not a ChainerCV problem, therefore closing this issue.
