### ISSUE TITLE
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainercv#359]
https://github.com/chainer/chainer/files/1176469/install_chainer.zip
this is my install chainer with -vvvv option

**Comment by sharpstill** [comment]
Traceback (most recent call last):
  File "chainercv/trainer/train.py", line 192, in <module>
    main()
  File "chainercv/trainer/train.py", line 188, in main
    trainer.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/training/trainer.py", line 296, in run
    update()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/training/updater.py", line 177, in update
    self.update_core()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/training/updater.py", line 306, in update_core
    loss = loss_func(*in_arrays)
  File "/home/machen/face_expr/chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py", line 77, in __call__
    features = self.faster_rcnn.extractor(imgs)
  File "/home/machen/face_expr/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py", line 288, in __call__
    h = func(h)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/links/connection/convolution_2d.py", line 154, in __call__
    x, self.W, self.b, self.stride, self.pad)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 439, in convolution_2d
    return func(x, W, b)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/function.py", line 327, in forward
    return self.forward_gpu(inputs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 151, in forward_gpu
    y_desc.value, y.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 692, in cupy.cuda.cudnn.convolutionForward
  File "cupy/cuda/cudnn.pyx", line 705, in cupy.cuda.cudnn.convolutionForward
  File "cupy/cuda/cudnn.pyx", line 417, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_MAPPING_ERROR: b'CUDNN_STATUS_MAPPING_ERROR'

**Comment by sharpstill** [comment]
I have struggled with it for whole day. But when I changed cudnn to v5.1 with cuda v8.0 still not help

**Comment by sharpstill** [comment]
help me please

**Comment by sharpstill** [comment]
>>> import cupy
>>> cupy.__version__
'1.0.1'
>>> import chainer 
>>> chainer.__version__
'2.0.1'

**Comment by yuyu2172** [comment]
This is an issue with Chainer and not with ChainerCV.
Please uninstall cupy and install it again.

**Comment by sharpstill** [comment]
```
@yuyu2172 I finnaly figure out what the problem is. I have modify your chainercv last classification layer which is num_class < 20 to fit my needs.
But when I load the optimizer model which I trained with the old_num_class=20 before.
I hit the problem, which report:
Traceback (most recent call last):
  File "elementwise_sample.py", line 61, in <module>
    )(x, y)
  File "cupy\core\elementwise.pxi", line 508, in cupy.core.core.ElementwiseKernel.__call__ (cupy\core\core.cpp:34118)
  File "cupy\core\elementwise.pxi", line 334, in cupy.core.core._broadcast (cupy\core\core.cpp:31734)
  File "cupy\core\core.pyx", line 1504, in cupy.core.core.broadcast.__init__ (cupy\core\core.cpp:50697)
ValueError: Broadcasting failed
```
**What the chainer.serializers.load_npz('./snapshot_optimizer.npz', optimizer) actually load?
what is stored inside ./snapshot_optimizer.npz?**
