### ISSUE TITLE
Test of RPN fails with GPU

### ISSUE THREAD

**Issue by Hakuyume** [chainer/chainercv#489]
```
======================================================================
ERROR: test_call_gpu (test_region_proposal_network.transplant_class.<locals>.C)  parameter: {'train': True}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/links_tests/model_tests/faster_rcnn_tests/test_region_proposal_network.py", line 83, in test_call_gpu
    chainer.cuda.to_gpu(self.x), self.img_size)
  File "tests/links_tests/model_tests/faster_rcnn_tests/test_region_proposal_network.py", line 43, in _check_call
    chainer.Variable(x), img_size)
  File "***/site-packages/chainercv-0.7.0-py3.6-linux-x86_64.egg/chainercv/links/model/faster_rcnn/region_proposal_network.py", line 111, in __call__
    self.xp.array(self.anchor_base), self.feat_stride, hh, ww)
  File "***/site-packages/chainercv-0.7.0-py3.6-linux-x86_64.egg/chainercv/links/model/faster_rcnn/region_proposal_network.py", line 152, in _enumerate_shifted_anchor
    shift_y.ravel(), shift_x.ravel()), axis=1)
  File "***/site-packages/cupy/manipulation/join.py", line 126, in stack
    'axis {} out of bounds [0, {})'.format(axis, x.ndim))
numpy.core._internal.AxisError: axis 1 out of bounds [0, 1)

======================================================================
```

**Comment by Hakuyume** [comment]
https://github.com/cupy/cupy/issues/793

**Comment by yuyu2172** [comment]
In the latest stable version (`Chainer==3.2.0 and CuPy==2.2.0`), this problem is fixed.
