### ISSUE TITLE
Techniques for debugging faster_rcnn errors

### ISSUE THREAD

**Issue by maxisme** [chainer/chainercv#564]
When running my `faster_rcnn` at a random time maybe an hour into training I am getting the traceback:

```
Traceback (most recent call last):
  File "train_face_localisation.py", line 102, in <module>
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/trainer.py", line 306, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/optimizer.py", line 659, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py", line 123, in __call__
    features, sample_roi, sample_roi_index)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py", line 221, in __call__
    fc6 = F.relu(self.fc6(pool))
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/links/connection/linear.py", line 129, in __call__
    return linear.linear(x, self.W, self.b)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/functions/connection/linear.py", line 227, in linear
    x = x.reshape(len(x), -1)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/variable.py", line 1104, in reshape
    return chainer.functions.reshape(self, shape)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/functions/array/reshape.py", line 98, in reshape
    y, = Reshape(shape).apply((x,))
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/function_node.py", line 255, in apply
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/functions/array/reshape.py", line 44, in forward
    return x.reshape(self.shape),
  File "cupy/core/core.pyx", line 486, in cupy.core.core.ndarray.reshape
  File "cupy/core/core.pyx", line 459, in cupy.core.core.ndarray._reshape
  File "cupy/core/internal.pyx", line 139, in cupy.core.internal.infer_unknown_dimension
ZeroDivisionError: integer division or modulo by zero
```
and the model stops training. I have no idea how I should go about debugging this error any tips would be appreciated!

**Comment by yuyu2172** [comment]
Probably, the RPN is producing empty ROIs.

**Comment by maxisme** [comment]
What can I do about that?

**Comment by yuyu2172** [comment]
Possibly, there is a bug in your dataset like the convention of bbox.
If that is not the problem, you may need to adjust hyperparameters.

**Comment by maxisme** [comment]
In the `get_example` function should I return None if there are any sort of errors like this:
```
    def get_example(self, i):
        img_path = self.paths[i]

        try:
            bbox = self.bboxs[img_path].astype(np.float32)
            labels = np.zeros(len(bbox), dtype=np.int32)
        except:
            return None, None, None

        img = read_image(img_path, color=True)

        return img, bbox, labels
```

**Comment by maxisme** [comment]
I am also getting the error:
```
/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/utils/proposal_creator.py:126: RuntimeWarning: invalid value encountered in greater_equal
  keep = np.where((hs >= min_size) & (ws >= min_size))[0].....]  5.76%
760         0           328.24                    nan         nan                nan                nan                nan    
```
and all logging is then returning `nan`

**Comment by maxisme** [comment]
I cannot for the life of me which piece of data is causing these errors to be thrown:

```
  File "train_face_localisation.py", line 103, in <module>
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/trainer.py", line 320, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/trainer.py", line 306, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/updaters/standard_updater.py", line 149, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/training/updaters/standard_updater.py", line 160, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/local/lib/python2.7/dist-packages/chainer-4.0.0b4-py2.7.egg/chainer/optimizer.py", line 659, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/faster_rcnn_train_chain.py", line 120, in __call__
    self.loc_normalize_mean, self.loc_normalize_std)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/utils/proposal_target_creator.py", line 135, in __call__
    gt_roi_loc = bbox2loc(sample_roi, bbox[gt_assignment[keep_index]])
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/utils/bbox2loc.py", line 55, in bbox2loc
    dy = (base_ctr_y - ctr_y) / height
```
Please help.

**Comment by maxisme** [comment]
I have checked every single bbox and removed all the ones that equal zero when subtracting.
